mozilla/assay

.c8rc
.eslintrc.json
CHANGELOG.md
README.md
src/amo/commands/fetch.ts
src/amo/commands/updateTaskbar.ts
src/amo/types.ts
src/amo/utils/addonDownload.ts
src/amo/utils/addonExtract.ts
src/amo/utils/addonInfo.ts
src/amo/utils/addonVersions.ts
src/config/config.ts
src/config/constants.ts
src/test/suite/utils/AddonDownload.test.ts
src/test/suite/utils/AddonExtract.test.ts
src/test/suite/utils/AddonInfo.test.ts
webpack.config.js

Fixes some of #2 and #3 
Have not
- Remade folder structure
- Better error handling
- Cached review url links  
In terms of cached review links, we actually have the review url stored in the `addonInfoResponse` type, so caching can completely do away with current implementation in `updateTaskbar.ts`. Auth can be handled when fetching addons (to show non-public versions) instead of the review page item.

Make code quality improvements

---

.vscode/launch.json
README.md
package-lock.json
package.json
src/config/config.ts
src/test/suite/utils/AddonDownload.test.ts
webpack.config.js

View the readme for instructions on how to use env variables. This PR is to allow the changing of environment during development. Currently, only urls are changed do dev, stage, prod depending on the NODE_ENV variable.

Add env variables for development modes

---

src/amo/commands/getAddon.ts
src/amo/utils/addonDownload.ts
src/amo/utils/addonExtract.ts
src/amo/utils/addonInfo.ts
src/amo/utils/addonVersions.ts
src/amo/utils/processErrors.ts
src/test/suite/commands/getAddon.test.ts
src/test/suite/utils/AddonDownload.test.ts
src/test/suite/utils/AddonExtract.test.ts
src/test/suite/utils/AddonInfo.test.ts
src/test/suite/utils/addonVersions.test.ts

(excludes `updateTaskbar.ts` due to cache branch)
No more do we check for random undefineds and check the same thing multiple times. Some errors are handled by asking the user if they want to try again, restart the process, or cancel altogether. These were all added to the tests (painstakingly). Some test formats changed and made more efficient (shared resources among tests).
Currently, all errors are caught in the `downloadAndExtract` try/catch since these functions all work in one process only. This function also became impossible to mock (still am unable to mock user-made functions properly), so some of it remains "untested" (each piece is already tested separately)
[Jira](https://mozilla-hub.atlassian.net/browse/AOP-116)

Update error handling with tests

---

package-lock.json
package.json
src/amo/commands/getApiCreds.ts
src/amo/extension.ts
src/amo/types.ts
src/amo/utils/addonDownload.ts
src/amo/utils/addonExtract.ts
src/amo/utils/addonInfo.ts
src/amo/utils/addonVersions.ts
src/amo/utils/processErrors.ts
src/amo/utils/requestAuth.ts
src/amo/views/sidebarView.ts
src/config/globals.ts
src/test/suite/commands/getApiCreds.test.ts
src/test/suite/utils/AddonDownload.test.ts
src/test/suite/utils/AddonInfo.test.ts
src/test/suite/utils/addonVersions.test.ts
src/test/suite/utils/requestAuth.test.ts
src/test/suite/views/sidebarView.test.ts
webpack.config.js

This PR allows the user to input their key and secret in (stored with keytar) to fetch and download unlisted addons. Since we now have error messages to do with auth, I updated how they are made as well.
The key and secret input boxes are accessible from the sidebar. Ideally, they are asked on the fly when fetching an addon. However, the vscode input box api does not stay focused when clicking off the screen. This means the user cannot go and copy their code then come back without ending the process.
The `showErrorMessage` function takes in an object of the possible responses depending on the status of the response (tried to cut down on the amount of if branches there are).
The requests ask for the unlisted addon versions (filter=all_with_unlisted). Should they also ask for the deleted …

Implement authentication.

---

src/utils/addonDownload.ts
src/utils/addonExtract.ts
src/utils/addonInfo.ts
src/utils/addonVersions.ts
test/suite/commands/getAddon.test.ts
test/suite/commands/getApiCreds.test.ts
test/suite/commands/updateTaskbar.test.ts
test/suite/extension.test.ts
test/suite/utils/AddonDownload.test.ts
test/suite/utils/AddonExtract.test.ts
test/suite/utils/AddonInfo.test.ts
test/suite/utils/addonCache.test.ts
test/suite/utils/addonVersions.test.ts
test/suite/utils/requestAuth.test.ts
test/suite/utils/reviewRootDir.test.ts
test/suite/views/sidebarView.test.ts

I've given all stubs proper names, took out constants and functions for readability, utilized beforeEach and afterEach for setup and cleanup instead of doing it in each test. the addonVersions tests are a little messy due to the fetch stubs, but trying to make a common variable between them didn't help much with line efficiency. I removed the individual tests for the errors since they can all be done with one test of the actual error function. Anything else for the tests that I should change? 
Also, I was missing return statements for the error functions, just added that back in.

Fix up tests

---

.c8rc
package.json
src/commands/launchDiff.ts
src/extension.ts
src/utils/addonExtract.ts
src/utils/diffTool.ts
test/suite/commands/launchDiff.test.ts
test/suite/utils/AddonExtract.test.ts
test/suite/utils/diffTool.test.ts

The user can input their own command that will automatically have the arguments of the filepaths filled for their own diff tool. It also shows the "Open in diff tool" in the right click menu ONLY if there are exactly two folders selected.
Temporarily removed read-only feature as that causes issues with some tools.

Third party diff tool launching

---

src/commands/loadComments.ts
src/commands/makeComment.ts
src/config/globals.ts
src/extension.ts
src/utils/addonCache.ts
src/views/fileDecorations.ts
test/suite/commands/loadComments.test.ts
test/suite/commands/makeComment.test.ts
test/suite/extension.test.ts
test/suite/utils/addonCache.test.ts
test/suite/views/fileDecorations.test.ts

The file tree now shows which files/folders have comments in them. To do this, I had to rework the cache to have layered keys depending on the path parts (so i could propagate upwards and quickly check if the folder has subcontents with comments). 
The cache also has a new function to remove empty keys. Previously, I just had "deleted" comments be an empty string, then ignored the empty string. Now, if a key has no value, that key is removed from the object. Then we check its parent to see if it still has values. This is much more like a proper cache.
the tree decorators are updated on load of the extension, when a new comment is made, when a comment is deleted, or when text editors are swapped.
The decorators are also quite easy to extend. When linting becomes a thing, we can have …

Add colourful tree indicators for comments in files

---

package.json
src/commands/deleteComment.ts
src/commands/makeComment.ts
src/extension.ts
test/suite/commands/deleteComment.test.ts
test/suite/extension.test.ts

You are now able to delete comments:
1. from the command palette. will remove the comment from the current line
2. from the context menu
3. from the make comment webview.
this works by making the comment of the current line blank, which `removeEmptyObjectsFromCache()` will catch and remove. Then it reloads the comments.
(also remove the assay introduction from the command palette for now)

Various delete comment methods

---

package.json
src/commands/getAddon.ts
src/commands/loadComments.ts
src/commands/openFromUrl.ts
src/extension.ts
src/utils/addonVersions.ts
test/suite/commands/getAddon.test.ts
test/suite/commands/openFromUrl.test.ts
test/suite/extension.test.ts
test/suite/utils/addonVersions.test.ts

This works by using registerUriHandler to transfer information from the browser to vscode. the link looks like `vscode://mozilla.assay/review/guid/version`
It will check to see if the manifest of the version exists in the set root path. If not, it will automatically download it and open it. if the version or guid is not specified, asks for those values after clicking the link.

Support vscode:// urls

---

package.json
src/commands/updateAssay.ts
src/extension.ts
src/utils/addonCache.ts
test/suite/commands/updateAssay.test.ts

This allows the user to check for updates with a command. It will check the latest release on github and if the release tag name (in the format x.x.x) does not match our current version number in package.json, will download and install the update. Finally, it will ask the user to reload vscode.
I'm not too familiar with github releases, this change requires the tag name to be formatted like x.x.x not vx.x.x. Is there any style that I should be following?

Updating assay version

---

package-lock.json
package.json
src/commands/openFromUrl.ts
src/config/globals.ts
src/extension.ts
test/suite/commands/openFromUrl.test.ts
test/suite/extension.test.ts

Fixes #30 
Before, the extension would download the addon properly but then only open the manifest as a file and not the folder that it resides in. This patch changes that. Due to limitations of workspace tinkering (the fact that there is one extension instance per workspace), the workaround is to save to storage the manifest path, launch a new workspace rooted at the proper folder, then have a startup listener to open the manifest path (see the [updateWorkspaceFolder documentation here](https://code.visualstudio.com/api/references/vscode-api#workspace)).
@vscode/test-electron had to be updated, some others follow.

Open the extension folder from URL not just manifest

---

src/commands/getApiCreds.ts
src/extension.ts
src/views/sidebarView.ts

Currently Assay does not show the user any feedback about any current credentials (API Key, API Secret). Additionally, there is no way to test API credentials save for attempting to use Assay features and having them fail. This make it difficult for the user to debug problems with credentials.
<details><summary><strong>Current UI screenshots</strong></summary>
**Previous version of the Enter API Key UI**
**Previous version of the Enter API Secret UI**
</details>
With this PR, Assay will now show the previous API Key and API Secret as placeholder text in the prompts. In the case of the secret, the placeholder value is a truncated version of the string that only revleas the first and last four characters of the secret separated by thee periods. For example, if the secret was …

Provide feedback when working with AMO credentails 

---

src/views/fileDecorations.ts

Fixes #38.
The deleted code was propagating the edit icon to the parent folders, but provideFileDecoration natively implements the ability to do so by just including propagate: true to the return object.
It no longer shows the icon on folders as propagate overwrites it (so I removed the logic relating to passing the icon to the folder), but it more closely follows VS Code’s native design just leaving this behaviour as is. With the boolean:
Versus the original:
And freshly generated .cpuprofile files to contrast the two:
[Original](https://share.firefox.dev/3WwmNY4) [With change](
https://share.firefox.dev/3yj8tbi)
The class was also missing the 'implements' keyword.

Fixed Issue Where File Decorator Hogs CPU

---

src/commands/getAddon.ts
src/utils/addonInfo.ts
src/utils/addonVersions.ts
src/utils/getAddonSlug.ts
test/suite/utils/getAddonSlug.test.ts
test/suite/utils/getAddonSlug.ts

Closes #34
**Changes**
- The API already takes the internal AMO ID, so it was just a matter of modifying the delimiter based on URL.

Added Support for AMO's Review Page URL When Opening an Add-on for Review

---

src/types.ts
src/utils/addonCache.ts
src/utils/addonExtract.ts
src/utils/commentManager.ts
src/utils/getDeleteCommentsPreference.ts
test/suite/utils/AddonExtract.test.ts
test/suite/utils/getDeleteCommentsPreference.test.ts

Closes #53 
**Changes**
- Changed areas that use QuickPicks to utilize an Enum `QPOption` for its options.

Replace QuickPick String Literals with String Enums

---

src/commands/updateTaskbar.ts

Fixes #40.
The actual reason was because the filepath changes when the user is using the commenting API, causing it not to match the root folder.

Fixed updateTaskbar.ts Filepath Error Throwing Constantly

---

src/views/rootView.ts
test/suite/controller/directoryController.test.ts
test/suite/views/rootView.test.ts

When no root folder exists, Assay prompts the user to select one. Since this is done every time the root folder is checked for, there is a chance this is the first thing the user encounters after installing Assay. Added a modal to explain the situation to the user before prompting to select a root folder to alleviate some confusion.
A future improvement could be to avoid these checks until the user completes setup through the Assay sidebar.

Add Prompt Before Opening File Dialog

---

package.json
src/controller/commentCacheController.ts
src/controller/commentController.ts
src/controller/diffController.ts
src/controller/sidebarController.ts
src/extension.ts
src/model/sidebarTreeDataProvider.ts
test/suite/controller/commentController.test.ts

**Changes**
- Moved exporting comments and deleting comments from the explorer menu to the dedicated Assay menu for consistency.
- When a version is deleted, deletes the comments stored in cache.

Moved "Export Comments" and "Delete Comments" Options to Sidebar Rather Than File Explorer

---

package.json

Fixes #94
---
I verified on macOS by installing the "command line tools" in Beyond Compare.

Set `bcompare` as the default diff tool

---

package.json
src/controller/addonCacheController.ts
src/controller/addonController.ts
src/controller/directoryController.ts
src/controller/lintController.ts
src/controller/urlController.ts
src/extension.ts
src/types.ts
src/views/lintView.ts
test/suite/controller/addonCacheController.test.ts
test/suite/controller/directoryController.test.ts
test/suite/controller/lintController.test.ts
test/suite/controller/urlController.test.ts
test/suite/views/lintView.test.ts

Closes #88
**Changes**
- Removes the read-only functionality from the linter system.
- Disables the linter on current and subsequent views when the user saves changes/deletes from the version. The linter messages can be activated again by overwriting the local version with a new install.

Allow Version Files to be Editable by Reviewers

---

test/suite/controller/commentController.test.ts

Looks like #104 needed to be rebased because it had a small stylistic issue. This PR fixes it now.

Run prettier on commentController.test.ts

---

README.md

`vsce` doesn't like SVGs in the README even though it's fine with the extension itself using them. See [here](https://github.com/gitpod-io/gitpod/issues/8030)
Fails`npm run build` -- 
`ERROR  SVGs are restricted in README.md; please use other file image formats, such as PNG: https://dl.circleci.com/status-badge/img/gh/mozilla/assay/tree/main.svg?style=svg`

Change CircleCI Status Badge to PNG rather than SVG

---

package.json

Closes #116
Avoids conflict with other extensions also putting their context commands at `navigation@1`, or at least as much as possible, without moving Assay's commands to the bottom of the context menu in its own section.

Fix: Prevent Context Menu Commands From Conflicting with Other Extensions

---

src/controller/commentCacheController.ts
src/controller/commentController.ts
src/controller/directoryController.ts
src/controller/statusBarController.ts
test/suite/controller/commentCacheController.test.ts
test/suite/controller/commentController.test.ts
test/suite/controller/directoryController.test.ts
test/suite/controller/statusBarController.test.ts

Fixes #120
**Changes**
- Changed how root folder is determined to be more strict
- Removed duplicate code relating to root folder checks, routing them all through helper functions\
- Changed `updateStatusBar()` from throwing errors to returning false (since it could do the prior constantly outside of addons folder and in regular VS Code use).

More Strictly Determine the Root Folder

---

src/controller/lintController.ts
test/suite/controller/lintController.test.ts

Fixes #128.
Handles the case where a certain lint does not have the 'file' attribute. Places the lint directly on the version folder.

Handle Case Where Fetched Lint does not have File Attribute

---

src/extension.ts
test/suite/extension.test.ts

Closes #124
**Changes**
- Avoids the complications with single files altogether by not allowing Assay to be used without a workspace.

Do Not Fully Initialize Assay if Not In Workspace

---

package.json

Relates to  #129
**Changes**
- Renames the Assay sidebar from 'Addons' to 'Assay' to stand out more.

Rename Assay Sidebar
